apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubero.fullname" . }}
  labels:
    {{- include "kubero.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubero.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubero.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          startupProbe: {{- toYaml .Values.startupProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/kubero
              name: kubero-config-volume
          env:
            # TODO: needs some investigation. Crashes with UNABLE_TO_VERIFY_LEAF_SIGNATURE
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: KUBERO_CONTEXT
              value: "{{ .Values.kubero.context }}"
            - name: KUBERO_NAMESPACE
              value: "{{ .Values.kubero.namespace }}"
            - name: KUBERO_WEBHOOK_URL
              value: "{{ .Values.kubero.webhook_url }}"
            - name: KUBERNETES_INGRESS_CLASSNAME
              value: "{{ .Values.ingress.className }}"
            - name: KUBERO_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: KUBERO_WEBHOOK_SECRET
            - name: KUBERO_USERS
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: KUBERO_USERS
                  optional: true
            - name: KUBERO_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: KUBERO_SESSION_KEY
                  optional: true
            - name: GITHUB_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GITHUB_PERSONAL_ACCESS_TOKEN
                  optional: true
            - name: GITEA_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GITEA_PERSONAL_ACCESS_TOKEN
                  optional: true
            - name: GITEA_BASEURL
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GITEA_BASEURL
                  optional: true
            - name: GITLAB_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GITLAB_PERSONAL_ACCESS_TOKEN
                  optional: true
            - name: GITLAB_BASEURL
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GITLAB_BASEURL
                  optional: true
            - name: GOGS_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GOGS_PERSONAL_ACCESS_TOKEN
                  optional: true
            - name: GOGS_BASEURL
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GOGS_BASEURL
                  optional: true
            - name: BITBUCKET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: BITBUCKET_USERNAME
                  optional: true
            - name: BITBUCKET_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: BITBUCKET_APP_PASSWORD
                  optional: true
            - name: KUBECONFIG_BASE64
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: KUBECONFIG_BASE64
                  optional: true
            {{- if .Values.kubero.auth.github.enabled }}
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              value: {{ .Values.kubero.auth.github.id | quote }}
            - name: GITHUB_CLIENT_CALLBACKURL
              value: {{ .Values.kubero.auth.github.callbackUrl | quote }}
            - name: GITHUB_CLIENT_ORG
              value: {{ .Values.kubero.auth.github.org | quote }}
            {{- end }}
            {{- if .Values.kubero.auth.oauth2.enabled }}
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubero-secrets
                  key: OAUTH2_CLIENT_SECRET
            - name: OAUTO2_CLIENT_NAME
              value: {{ .Values.kubero.auth.oauth2.name | quote }}
            - name: OAUTH2_CLIENT_ID
              value: {{ .Values.kubero.auth.oauth2.id | quote }}
            - name: OAUTO2_CLIENT_AUTH_URL
              value: {{ .Values.kubero.auth.oauth2.authUrl | quote }}
            - name: OAUTO2_CLIENT_TOKEN_URL
              value: {{ .Values.kubero.auth.oauth2.tokenUrl | quote }}
            - name: OAUTH2_CLIENT_CALLBACKURL
              value: {{ .Values.kubero.auth.oauth2.callbackUrl | quote }}
            {{- end }}
            - name: DEBUG
              value: "{{ .Values.kubero.debug }}"
            - name: KUBERO_CONFIG_PATH
              value: /etc/kubero/config.yaml
            - name: PORT
              value: "{{ .Values.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kubero-config-volume
          configMap:
            name: kubero-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}